// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (*Author, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (*Book, error)
	DeleteAuthor(ctx context.Context, id uuid.UUID) error
	DeleteBook(ctx context.Context, id uuid.UUID) error
	DeleteBooksByAuthorID(ctx context.Context, authorID uuid.UUID) error
	FindAuthors(ctx context.Context) ([]*Author, error)
	FindBooksByAuthorID(ctx context.Context, authorID uuid.UUID) ([]*Book, error)
	GetAuthorByID(ctx context.Context, id uuid.UUID) (*Author, error)
	GetBookByID(ctx context.Context, id uuid.UUID) (*Book, error)
	TotalAuthors(ctx context.Context) (int64, error)
	TotalBooks(ctx context.Context) (int64, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (*Author, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (*Book, error)
}

var _ Querier = (*Queries)(nil)
