// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteBooksByAuthorID = `-- name: DeleteBooksByAuthorID :exec
DELETE FROM books WHERE "author_id"=$1
`

func (q *Queries) DeleteBooksByAuthorID(ctx context.Context, authorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBooksByAuthorID, authorID)
	return err
}
