// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: books.sql

package repo_books

import (
	"context"

	"github.com/google/uuid"
)

const deleteByAuthorID = `-- name: DeleteByAuthorID :exec
DELETE FROM books WHERE "author_id"=$1
`

func (q *Queries) DeleteByAuthorID(ctx context.Context, authorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteByAuthorID, authorID)
	return err
}
