// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repo_books

import (
	"context"

	"github.com/google/uuid"
	. "github.com/sxwebdev/pgxgen-example/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*Book, error)
	Delete(ctx context.Context, id uuid.UUID) error
	DeleteByAuthorID(ctx context.Context, authorID uuid.UUID) error
	GetBookByID(ctx context.Context, id uuid.UUID) (*Book, error)
	Total(ctx context.Context) (int64, error)
	Update(ctx context.Context, arg UpdateParams) (*Book, error)
}

var _ Querier = (*Queries)(nil)
