// Code generated by pgxgen. DO NOT EDIT.
// versions:
//   pgxgen v0.1.0

package repo_authors

type TableName string

func (s TableName) String() string {
	return string(s)
}

const (
	TableNameAuthors TableName = "authors"
)
